name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is up!"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Run ESLint
        run: npx eslint .

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config auto .

      - name: Run Node.js Tests
        run: npm test --coverage
